/**
 * ML Model Metrics Service
 * Reads and serves trained model metrics from Python training script
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const METRICS_PATH = path.join(__dirname, '../../ml/models/metrics.json');

/**
 * Load model metrics from the JSON file generated by Python training script
 */
export const loadModelMetrics = () => {
  try {
    if (!fs.existsSync(METRICS_PATH)) {
      console.warn('Model metrics file not found. Please train the model first.');
      return null;
    }

    const metricsData = fs.readFileSync(METRICS_PATH, 'utf-8');
    const metrics = JSON.parse(metricsData);

    return metrics;
  } catch (error) {
    console.error('Error loading model metrics:', error);
    return null;
  }
};

/**
 * Get model performance summary
 */
export const getModelPerformance = () => {
  const metrics = loadModelMetrics();

  if (!metrics) {
    return {
      status: 'not_trained',
      message: 'Model has not been trained yet. Please run the training script.',
    };
  }

  return {
    status: 'trained',
    model_type: metrics.model_type,
    last_trained: metrics.timestamp,
    performance: {
      train_accuracy: metrics.accuracy.train,
      test_accuracy: metrics.accuracy.test,
      precision: metrics.metrics.precision,
      recall: metrics.metrics.recall,
      f1_score: metrics.metrics.f1_score,
    },
    dataset: {
      total_samples: metrics.dataset.total_samples,
      train_samples: metrics.dataset.train_samples,
      test_samples: metrics.dataset.test_samples,
      test_split_ratio: metrics.dataset.split_ratio,
    },
  };
};

/**
 * Get training accuracy percentage
 */
export const getTrainingAccuracy = () => {
  const metrics = loadModelMetrics();
  
  if (!metrics) {
    return null;
  }

  return {
    accuracy: metrics.accuracy.train.toFixed(2),
    sample_count: metrics.dataset.train_samples,
  };
};

/**
 * Get test accuracy percentage
 */
export const getTestAccuracy = () => {
  const metrics = loadModelMetrics();
  
  if (!metrics) {
    return null;
  }

  return {
    accuracy: metrics.accuracy.test.toFixed(2),
    sample_count: metrics.dataset.test_samples,
  };
};

/**
 * Get overall model statistics
 */
export const getModelStats = () => {
  const performance = getModelPerformance();

  if (performance.status === 'not_trained') {
    return performance;
  }

  return {
    ...performance,
    summary: {
      train_accuracy_percentage: performance.performance.train_accuracy.toFixed(2) + '%',
      test_accuracy_percentage: performance.performance.test_accuracy.toFixed(2) + '%',
      precision_percentage: performance.performance.precision.toFixed(2) + '%',
      recall_percentage: performance.performance.recall.toFixed(2) + '%',
      f1_score_percentage: performance.performance.f1_score.toFixed(2) + '%',
    },
  };
};

/**
 * Check if model is trained
 */
export const isModelTrained = () => {
  return fs.existsSync(METRICS_PATH);
};

/**
 * Watch for metrics file changes and reload
 */
export const watchMetricsFile = (callback) => {
  const metricsDir = path.dirname(METRICS_PATH);
  
  if (!fs.existsSync(metricsDir)) {
    console.warn('Metrics directory does not exist yet.');
    return null;
  }

  const watcher = fs.watch(metricsDir, (eventType, filename) => {
    if (filename === 'metrics.json' && eventType === 'change') {
      console.log('Model metrics updated. Reloading...');
      const metrics = loadModelMetrics();
      if (callback && metrics) {
        callback(metrics);
      }
    }
  });

  return watcher;
};

export default {
  loadModelMetrics,
  getModelPerformance,
  getTrainingAccuracy,
  getTestAccuracy,
  getModelStats,
  isModelTrained,
  watchMetricsFile,
};
